name: Migration test workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test database
        run: docker-compose up -d
      - name: Run migration on test database
        run: docker-compose --profile flyway up --exit-code-from flyway
      - name: Run unit tests
        run: docker-compose --profile pgtap up --exit-code-from pgtap

